plugins {
    id 'java-gradle-plugin'
}

dependencies {
    implementation project(':core')
}

gradlePlugin {
    automatedPublishing = false // Disable automated publishing to avoid issues with GitHub Packages
    plugins {
        glslPlugin {
            id = 'com.niwer.glsl_obfuscator'
            implementationClass = 'com.niwer.gradle.GradleGlslObfuscatorPlugin' // Main plugin class that implements Plugin<Project>
        }
    }
}

publishing {
    publications {
        gpr(MavenPublication) {
            artifactId = 'glsl-obfuscator-gradle-plugin'
            from components.java
        }
    }
}
