plugins {
    id 'java-gradle-plugin'
}

dependencies {
    implementation project(':core')
}

gradlePlugin {
    automatedPublishing = false // Disable automated publishing to avoid issues with GitHub Packages
    plugins {
        glslPlugin {
            id = 'com.niwer.glsl_obfuscator'
            implementationClass = 'com.niwer.glsl_obfuscator.gradle.GradleGlslObfuscatorPlugin' // Main plugin class that implements Plugin<Project>
        }
    }
}

tasks.named('jar', Jar) {
    from(project(':core').sourceSets.main.output) // Create a fat jar including the core module (We can do this without using the shadow plugin since Core isn't that big)
}

publishing {
    publications {
        gpr(MavenPublication) {
            artifactId = 'glsl-obfuscator-gradle-plugin'
            from components.java
        }
    }
}
