name: Release and Publish

on:
  push:
    tags:
      - 'v*' # Triggers when receiving a tag push such as v1.0.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Maven authentification

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests (JUnit)
        run: ./gradlew test

      - name: Prepare Fixed Name JARs
        run: |
          mkdir -p release-artifacts

          # Copy the JARs of the core library
          cp $(ls core/build/libs/*.jar | grep -v -- '-sources\.jar$' | head -n 1) release-artifacts/glsl-obfuscator-core.jar
          cp core/build/libs/*-sources.jar release-artifacts/glsl-obfuscator-core-sources.jar

          # Copy the JARs of the Gradle plugin
          cp $(ls gradle-plugin/build/libs/*.jar | grep -v -- '-sources\.jar$' | head -n 1) release-artifacts/glsl-obfuscator-gradle-plugin.jar
          cp gradle-plugin/build/libs/*-sources.jar release-artifacts/glsl-obfuscator-gradle-plugin-sources.jar

          # Copy the JARs of the Maven plugin
          cp $(ls maven-plugin/build/libs/*.jar | grep -v -- '-sources\.jar$' | head -n 1) release-artifacts/glsl-obfuscator-maven-plugin.jar
          cp maven-plugin/build/libs/*-sources.jar release-artifacts/glsl-obfuscator-maven-plugin-sources.jar

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
